# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://menchaojie.github.io
date_format: "ordinal"
title: 方下
subtitle: "闲来地方小，身合天下宽"
description: "时间因相对而生，过往未来皆是现在"
keywords: menchaojie, 身合, coding, 心修, happy, 回归
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2024
# 源码仓库，请替换成自己的
repository: menchaojie/menchaojie.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2024-06-08
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: false 
        image_alt: 诚心
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate 
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
# highlight_theme: github
# highlight_theme: magritte 
highlight_theme: github.dark 

# ---------------- #
#      Author      #
# ---------------- #
author: Chaojie Men
organization: 
organization_url: 
github_username: menchaojie
location: Shanghai, China
email: menchaojie@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /open-source/
    label: 开源
    mobile-hidden: true

  -
    href: /fragments/
    label: 片段

  -
    href: /wiki/
    # label: 维基
    # 感觉这个目录下的内容和wiki很不融洽
    label: 百科

  -
    href: /links/
    label: 链接
    mobile-hidden: true

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
    banner:
        # 首页 banner 区文字颜色
        # color: "#fff"
        color: "#F1F0ED"
        # 首页导航栏文字颜色
        nav-color: "rgba(255, 255, 255, .5)"
        # 首页 banner 区背景颜色
        # background-color: "#4183c4"
        # background-color: "#2983BB"
        background-color: "#2775B6"
        # 首页 banner 区背景图片
        # background-image: "/assets/images/octicons-bg.png"
        # background-repeat: "no-repeat"
        # background-size: "cover"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
# highlighter: rouge
highlighter: gruvbox.light
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# disqus 配置参考：https://disqus.com
disqus:
    username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: mzlogin
    repo: blog-comments
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: mzlogin/blog-comments
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: mzlogin/blog-comments
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: menchaojie/menchaojie.github.io
    repo-id: R_kgDOMG3kMQ
    category: Announcements
    category-id: DIC_kwDOMG3kMc4Cf91T
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
